name: venturiautospurghi
description: All rights rightly right

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.0+43

#config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12' to podfile

environment:
  sdk: ">=2.14.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

#  url_launcher: ^5.7.10

  font_awesome_flutter: ^9.2.0
  http: any
  simple_animations: ^5.0.2

  google_sign_in: ^5.2.1
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  cloud_functions: ^4.3.1

  intl: ^0.18.1
  flutter_bloc: ^8.0.1
  json_annotation: ^4.0.0
  uuid: ^3.0.1
  equatable: ^2.0.0
  file_picker: ^3.0.0
  flutter_downloader: ^1.7.1
  permission_handler: ^9.2.0
  path: ^1.8.0
  google_place: ^0.4.0
  url_strategy: ^0.2.0
  pdf: ^3.10.4
  printing: ^5.11.0

  #mobile only
  url_launcher: ^6.0.2
  launch_review: ^3.0.1
  fluttertoast: ^8.0.3
  path_provider: ^2.0.1
  simple_gesture_detector: ^0.2.0
  package_info: ^2.0.0
#  sms_autofill: ^1.3.1
  
  #web only
  js: ^0.6.3
  datetime_picker_formfield: ^2.0.0
  go_router: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path_android: "assets/icona-app.png"
  image_path: "assets/logo-venturi.png"
  android: true
  ios: true
  web: true

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/logo.png
    - assets/icona-app.png
    - assets/no-events-image.png
    - assets/contratto.png
    - assets/intervento.png